services:
  database:
    image: postgres:17
    container_name: database
    env_file:
      - .env
    ports:
      - "54332:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  application:
    image: gestor-teocratico
    container_name: gestor-teocratico
    build:
      context: .
      dockerfile: GestorTeocratico/Dockerfile
    env_file:
      - .env
    depends_on:
      - database
    ports:
      - "8080:8080"

volumes:
  postgres_data: